version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./certificates:/etc/nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    working_dir: /var/www
